version: '3'

services:

  apache:
    build: php
    environment:
      - DB_HOST=MYSQL
      - DB_NAME=appDB
      - DB_USER=user
      - DB_PASSWORD=password
    container_name: APACHE
    volumes:
      - ./src:/var/www/html
      - ./httpd/httpd.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./storage:/var/www/storage
    depends_on:
      - mysql

  nginx:
    image: nginx
    container_name: NGINX
    ports:
      - 80:80
    volumes:
      - ./static:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - apache
  
  mysql:
    container_name: MYSQL
    hostname: MYSQL
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      HOSTNAME: MYSQL
    volumes:
       - "./sql:/docker-entrypoint-initdb.d"
       - "./dbdata:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 10

  redis:
    container_name: REDIS
    image: redis:alpine3.16
    restart: always
    ports:
      - 6379:6379
    depends_on:
      - apache

  redis-commander:
    container_name: REDIS-COMMANDER
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

volumes:
  dbdata:

